DUK_USE_BUFFEROBJECT_SUPPORT: true

# Error reporting
DUK_USE_VERBOSE_ERRORS: true
DUK_USE_TRACEBACKS: true
DUK_USE_AUGMENT_ERROR_CREATE: true
DUK_USE_FUNC_FILENAME_PROPERTY: true
DUK_USE_PC2LINE: true

DUK_USE_ROM_STRINGS: true
DUK_USE_ROM_OBJECTS: true
DUK_USE_ROM_GLOBAL_INHERIT: true

DUK_USE_FAST_REFCOUNT_DEFAULT: true
DUK_USE_BASE64_SUPPORT: true
